spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:aurora-db-sharding.yaml
    hikari:
      pool-name: aurora-user-pool
      minimum-idle: 150
      maximum-pool-size: 300
      idle-timeout: 60000
      connection-init-sql: select 1
      connection-timeout: 4000
      max-lifetime: 60000
  application:
    name: aurora-live-user-application

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://halo.test.com:8848?namespace=aurora-live-test&&username=root&&password=halo_nacos
  protocol:
    name: dubbo
    port: 9090